<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="haile" failures="6" tests="8" name="TestAddController" time="14.271" errors="0" timestamp="2021-12-05T22:14:10 ICT">
  <testcase classname="testController.AddControllerTest" name="adduserTest_TC01_Failed" time="0.031">
    <failure type="org.testng.TestException" message="
Method AddControllerTest.adduserTest_TC01_Failed()[pri:0, instance:testController.AddControllerTest@5812f68b] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method AddControllerTest.adduserTest_TC01_Failed()[pri:0, instance:testController.AddControllerTest@5812f68b] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- adduserTest_TC01_Failed -->
  <testcase classname="testController.AddControllerTest" name="adduserTest_TC02_Failed" time="0.002">
    <failure type="org.testng.TestException" message="
Method AddControllerTest.adduserTest_TC02_Failed(java.lang.String)[pri:0, instance:testController.AddControllerTest@5812f68b] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method AddControllerTest.adduserTest_TC02_Failed(java.lang.String)[pri:0, instance:testController.AddControllerTest@5812f68b] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- adduserTest_TC02_Failed -->
  <testcase classname="testController.AddControllerTest" name="adduserTest_TC03_Failed" time="0.003">
    <failure type="org.testng.TestException" message="
Method AddControllerTest.adduserTest_TC03_Failed(java.lang.String)[pri:0, instance:testController.AddControllerTest@5812f68b] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method AddControllerTest.adduserTest_TC03_Failed(java.lang.String)[pri:0, instance:testController.AddControllerTest@5812f68b] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- adduserTest_TC03_Failed -->
  <testcase classname="testController.AddControllerTest" name="adduserTest_TC04_Failed" time="0.001">
    <failure type="org.testng.TestException" message="
Method AddControllerTest.adduserTest_TC04_Failed()[pri:0, instance:testController.AddControllerTest@5812f68b] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method AddControllerTest.adduserTest_TC04_Failed()[pri:0, instance:testController.AddControllerTest@5812f68b] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- adduserTest_TC04_Failed -->
  <testcase classname="testController.AddControllerTest" name="adduserTest_TC05_Success" time="0.002"/>
  <testcase classname="testController.AddControllerTest" name="getcodeTest" time="0.009"/>
  <testcase classname="testController.AddControllerTest" name="getlistuserTest" time="0.025">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;1&amp;gt; but was:&amp;lt;0&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<1> but was:<0>
at testController.AddControllerTest.getlistuserTest(AddControllerTest.java:107)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- getlistuserTest -->
  <testcase classname="testController.AddControllerTest" name="sendmailTest" time="12.077">
    <failure type="java.lang.LinkageError" message="loader constraint violation in interface itable initialization for class javax.swing.JComponent$1: when selecting method &amp;apos;boolean sun.swing.SwingAccessor$JComponentAccessor.getFlag(javax.swing.JComponent, int)&amp;apos; the class loader &amp;apos;bootstrap&amp;apos; for super interface sun.swing.SwingAccessor$JComponentAccessor, and the class loader org.powermock.core.classloader.javassist.JavassistMockClassLoader @73ee04c8 of the selected method&amp;apos;s class, javax.swing.JComponent$1 have different Class objects for the type javax.swing.JComponent used in the signature (sun.swing.SwingAccessor$JComponentAccessor is in module java.desktop of loader &amp;apos;bootstrap&amp;apos;; javax.swing.JComponent$1 is in unnamed module of loader org.powermock.core.classloader.javassist.JavassistMockClassLoader @73ee04c8, parent loader &amp;apos;app&amp;apos;)">
      <![CDATA[java.lang.LinkageError: loader constraint violation in interface itable initialization for class javax.swing.JComponent$1: when selecting method 'boolean sun.swing.SwingAccessor$JComponentAccessor.getFlag(javax.swing.JComponent, int)' the class loader 'bootstrap' for super interface sun.swing.SwingAccessor$JComponentAccessor, and the class loader org.powermock.core.classloader.javassist.JavassistMockClassLoader @73ee04c8 of the selected method's class, javax.swing.JComponent$1 have different Class objects for the type javax.swing.JComponent used in the signature (sun.swing.SwingAccessor$JComponentAccessor is in module java.desktop of loader 'bootstrap'; javax.swing.JComponent$1 is in unnamed module of loader org.powermock.core.classloader.javassist.JavassistMockClassLoader @73ee04c8, parent loader 'app')
at javax.swing.JComponent.<clinit>(JComponent.java:381)
at testController.AddController.sendmail(AddController.java:59)
at testController.AddControllerTest.sendmailTest(AddControllerTest.java:114)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- sendmailTest -->
</testsuite> <!-- TestAddController -->
